from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re
import shutil
import subprocess

from logical.schema import ClaimRecord, ConstraintRecord, KnowledgeStatus, QueryIntent

SAFE_ATOM = re.compile(r"^[a-z][a-z0-9_]*$")


@dataclass(frozen=True)
class PrologCheckResult:
    ok: bool
    message: str


def project_world(
    claims: list[ClaimRecord], constraints: list[ConstraintRecord]
) -> str:
    lines = [
        "% Generated by logical. Do not edit by hand.",
        ":- table triple/3, neg_triple/3.",
        ":- dynamic triple/3, neg_triple/3, universal_rule/4, functional_for_subject/2.",
        ":- discontiguous triple/3, neg_triple/3, universal_rule/4, functional_for_subject/2.",
        "",
    ]
    facts = set()
    for claim in claims:
        if claim.status is not KnowledgeStatus.ACCEPTED:
            continue
        if claim.scope == "all":
            sign = "positive" if claim.polarity else "negative"
            facts.add(
                f"universal_rule({atom(claim.s)},{atom(claim.p)},{atom(claim.o)},{sign})."
            )
        elif claim.scope == "fact":
            predicate = "triple" if claim.polarity else "neg_triple"
            facts.add(f"{predicate}({atom(claim.s)},{atom(claim.p)},{atom(claim.o)}).")
    lines.extend(sorted(facts))
    lines.extend(
        sorted(
            {
                f"functional_for_subject({atom(c.s)},{atom(c.p)})."
                for c in constraints
                if c.kind == "functional_for_subject"
            }
        )
    )
    lines.extend(
        [
            "",
            "triple(A,subclass_of,C) :- triple(A,subclass_of,B), triple(B,subclass_of,C).",
            "triple(X,instance_of,C) :- triple(X,instance_of,B), triple(B,subclass_of,C).",
            "triple(X,P,O) :- triple(X,instance_of,C), universal_rule(C,P,O,positive).",
            "neg_triple(X,P,O) :- triple(X,instance_of,C), universal_rule(C,P,O,negative).",
            "contradiction(S,P,O) :- triple(S,P,O), neg_triple(S,P,O).",
            "functional_conflict(S,P,O1,O2) :- functional_for_subject(S,P), triple(S,P,O1), triple(S,P,O2), O1 \\= O2.",
            "",
        ]
    )
    return "\n".join(lines)


def atom(value: str) -> str:
    if SAFE_ATOM.fullmatch(value):
        return value
    return (
        "'"
        + value.replace("\\", "\\\\")
        .replace("'", "\\'")
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        + "'"
    )


def query_for_intent(intent: QueryIntent) -> str:
    predicate = "triple" if intent.polarity else "neg_triple"
    return f"{predicate}({atom(intent.s)},{atom(intent.p)},{atom(intent.o)})"


def validate_with_swipl(world_path: str | Path) -> PrologCheckResult:
    swipl = shutil.which("swipl")
    if swipl is None:
        return PrologCheckResult(
            True, "ok (SWI-Prolog not installed; independent Prolog check skipped)"
        )
    goal = "(((current_predicate(contradiction/3),contradiction(_,_,_));(current_predicate(functional_conflict/4),functional_conflict(_,_,_,_))) -> halt(2); halt(0))"
    try:
        result = subprocess.run(
            [swipl, "-q", "-s", str(world_path), "-g", goal],
            capture_output=True,
            text=True,
            check=False,
            timeout=15,
        )
    except subprocess.TimeoutExpired:
        return PrologCheckResult(False, "SWI-Prolog validation timed out")
    if result.returncode == 0 and "ERROR:" not in result.stderr:
        return PrologCheckResult(
            True, "ok (syntax and logical consistency verified with SWI-Prolog)"
        )
    return PrologCheckResult(
        False,
        (
            result.stderr
            or result.stdout
            or "SWI-Prolog detected inconsistent knowledge"
        ).strip(),
    )


def run_swipl_query(world_path: str | Path, query: str) -> bool:
    swipl = shutil.which("swipl")
    if swipl is None:
        raise RuntimeError("swipl is not installed")
    goal = f"(({query}) -> writeln(true); writeln(false)), halt."
    try:
        result = subprocess.run(
            [swipl, "-q", "-s", str(world_path), "-g", goal],
            capture_output=True,
            text=True,
            check=False,
            timeout=15,
        )
    except subprocess.TimeoutExpired as exc:
        raise RuntimeError("SWI-Prolog query timed out") from exc
    if result.returncode != 0 or "ERROR:" in result.stderr or not result.stdout.strip():
        raise RuntimeError(
            (result.stderr or result.stdout or "empty Prolog result").strip()
        )
    return result.stdout.strip().splitlines()[-1] == "true"
