from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re
import shutil
import subprocess

from logical.schema import ClaimRecord, ConstraintRecord, KnowledgeStatus, QueryIntent


SAFE_ATOM = re.compile(r"^[a-z][a-z0-9_]*$")


@dataclass(frozen=True)
class PrologCheckResult:
    ok: bool
    message: str


def project_world(
    claims: list[ClaimRecord], constraints: list[ConstraintRecord]
) -> str:
    lines = [
        "% Generated by logical. Do not edit by hand.",
        ":- discontiguous triple/3.",
        ":- discontiguous neg_triple/3.",
        ":- discontiguous functional_for_subject/2.",
        "",
    ]
    for claim in claims:
        if claim.status is not KnowledgeStatus.ACCEPTED:
            continue
        predicate = "triple" if claim.polarity else "neg_triple"
        lines.append(
            f"{predicate}({atom(claim.s)},{atom(claim.p)},{atom(claim.o)})."
        )
    for constraint in constraints:
        if constraint.kind == "functional_for_subject":
            lines.append(
                f"functional_for_subject({atom(constraint.s)},{atom(constraint.p)})."
            )
    lines.extend(
        [
            "",
            "contradiction(S,P,O) :- triple(S,P,O), neg_triple(S,P,O).",
            (
                "functional_conflict(S,P,O1,O2) :- functional_for_subject(S,P), "
                "triple(S,P,O1), triple(S,P,O2), O1 \\= O2."
            ),
            "",
        ]
    )
    return "\n".join(lines)


def atom(value: str) -> str:
    if SAFE_ATOM.match(value):
        return value
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def query_for_intent(intent: QueryIntent) -> str:
    predicate = "triple" if intent.polarity else "neg_triple"
    return f"{predicate}({atom(intent.s)},{atom(intent.p)},{atom(intent.o)})"


def validate_with_swipl(world_path: str | Path) -> PrologCheckResult:
    swipl = shutil.which("swipl")
    if swipl is None:
        return PrologCheckResult(
            ok=True,
            message="ok (swipl not installed; syntax validation skipped)",
        )
    result = subprocess.run(
        [swipl, "-q", "-t", "halt", "-s", str(world_path)],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode == 0:
        return PrologCheckResult(ok=True, message="ok")
    return PrologCheckResult(
        ok=False, message=(result.stderr or result.stdout or "swipl failed").strip()
    )


def run_swipl_query(world_path: str | Path, query: str) -> bool:
    swipl = shutil.which("swipl")
    if swipl is None:
        raise RuntimeError("swipl is not installed")
    goal = f"(({query}) -> writeln(true); writeln(false)), halt."
    result = subprocess.run(
        [swipl, "-q", "-s", str(world_path), "-g", goal],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError((result.stderr or result.stdout).strip())
    return result.stdout.strip().splitlines()[-1] == "true"
